spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
       url : jdbc:h2:mem:example
       username : sa
       password :
       type: com.alibaba.druid.pool.DruidDataSource
       driver-class-name : org.h2.Driver
    cache:
       type: simple
    http:
      multipart:
        enabled: true
        max-file-size: 100Mb
hsweb:
    cors:
      enable: on
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
    authorize:
      jwt:
        id: test
        secret: dGVzdA==
#      filters:
#           "/swagger-ui.html": "authc"
    app:
      name: hsweb示例
      version: 3.0.0
    entity:
      mappings:
          -  source-base-package: org.hswebframework.web.entity.authorization
             target-base-package: org.hswebframework.web.entity.authorization
             mapping:
                UserEntity: SimpleUserEntity
server:
  port: 8081
logging:
  level:
    org.hswebframework: debug